### ISSUE TITLE
Folder Permissions

### ISSUE THREAD

**Issue by axi92** [Renegade-Master/zomboid-dedicated-server#17]
**Describe the bug**
I am starting this docker-compose file in an empty directory and the permissions are not set as in the log but the 
```
Creating network "project-zomboid_new_default" with the default driver
Creating project-zomboid_new_zomboid-server_1 ... done
Attaching to project-zomboid_new_zomboid-server_1
zomboid-server_1  |
zomboid-server_1  | ### Setting variables...
zomboid-server_1  |
zomboid-server_1  | ### Updating Folder Permissions...
zomboid-server_1  | chown: changing ownership of '/home/steam/ZomboidDedicatedServer': Operation not permitted
zomboid-server_1  | chown: changing ownership of '/home/steam/Zomboid': Operation not permitted
zomboid-server_1  |
zomboid-server_1  | ### Folder Permissions updated.
zomboid-server_1  |
zomboid-server_1  | ### Applying Pre Install Configuration...
zomboid-server_1  |
zomboid-server_1  | ### Pre Install Configuration applied.
zomboid-server_1  |
zomboid-server_1  | ### Updating Project Zomboid Server...
zomboid-server_1  | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
zomboid-server_1  | ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
zomboid-server_1  | [  0%] Checking for available update...
zomboid-server_1  | [----] Downloading update (0 of 54724 KB)...
zomboid-server_1  | [  0%] Downloading update (3071 of 54724 KB)...
zomboid-server_1  | [  5%] Downloading update (6731 of 54724 KB)...
zomboid-server_1  | [ 12%] Downloading update (9638 of 54724 KB)...
....
zomboid-server_1  | [----] Update complete, launching...
zomboid-server_1  | WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
zomboid-server_1  | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
zomboid-server_1  | /tmp/dumps insufficient permissions - delete and recreate
zomboid-server_1  | [  0%] Checking for available updates...
zomboid-server_1  | [----] Verifying installation...
zomboid-server_1  | Steam Console Client (c) Valve Corporation - version 1646418545
zomboid-server_1  | -- type 'quit' to exit --
zomboid-server_1  | Loading Steam API...OK
zomboid-server_1  | @ShutdownOnFailedCommand 0
zomboid-server_1  | "@ShutdownOnFailedCommand" = "0"
zomboid-server_1  | @NoPromptForPassword 1
zomboid-server_1  | "@NoPromptForPassword" = "1"
zomboid-server_1  | force_install_dir /home/steam/ZomboidDedicatedServer
zomboid-server_1  |
zomboid-server_1  | Connecting anonymously to Steam Public...Connectivity test: result=Connected, in progress=0
zomboid-server_1  | OK
zomboid-server_1  | Waiting for client config...OK
zomboid-server_1  | Waiting for user info...OK
zomboid-server_1  | app_update 380870 -beta public validate
zomboid-server_1  |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
zomboid-server_1  |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
zomboid-server_1  |  Update state (0x5) verifying install, progress: 25.78 (781732043 / 3032353055)
zomboid-server_1  |  Update state (0x5) verifying install, progress: 62.07 (1882098607 / 3032353055)
zomboid-server_1  |  Update state (0x11) preallocating, progress: 2.17 (65682901 / 3032353055)
zomboid-server_1  |  Update state (0x11) preallocating, progress: 3.11 (94314092 / 3032353055)
zomboid-server_1  |  Update state (0x11) preallocating, progress: 3.24 (98286214 / 3032353055)
zomboid-server_1  |  Update state (0x11) preallocating, progress: 22.27 (675417113 / 3032353055)
zomboid-server_1  |  Update state (0x11) preallocating, progress: 26.70 (809507665 / 3032353055)
zomboid-server_1  |  Update state (0x11) preallocating, progress: 48.59 (1473414630 / 3032353055)
zomboid-server_1  |  Update state (0x11) preallocating, progress: 94.55 (2866938745 / 3032353055)
zomboid-server_1  |  Update state (0x61) downloading, progress: 2.14 (64781155 / 3032353055)
zomboid-server_1  |  Update state (0x61) downloading, progress: 2.46 (74497813 / 3032353055)
...
zomboid-server_1  |  Update state (0x101) committing, progress: 58.57 (1776113674 / 3032353055)
zomboid-server_1  |  Update state (0x101) committing, progress: 91.78 (2782991596 / 3032353055)
zomboid-server_1  | Success! App '380870' fully installed.
zomboid-server_1  | quit
zomboid-server_1  |
zomboid-server_1  | ### Project Zomboid Server updated.
zomboid-server_1  |
zomboid-server_1  | ### Checking if this is the first run...
zomboid-server_1  |
zomboid-server_1  | ### This is the first run.
zomboid-server_1  | Starting server for 60 seconds
zomboid-server_1  |
zomboid-server_1  | ### Starting Project Zomboid Server...
zomboid-server_1  | timeout: failed to run command '/home/steam/ZomboidDedicatedServer/start-server.sh': No such file or directory
zomboid-server_1  |
zomboid-server_1  | ### First run check complete.
zomboid-server_1  |
zomboid-server_1  | ### Applying Post Install Configuration...
zomboid-server_1  | sed: can't read /home/steam/Zomboid/Server/SunnySideGaming.ini: No such file or directory
zomboid-server_1  | sed: can't read /home/steam/Zomboid/Server/SunnySideGaming.ini: No such file or directory
zomboid-server_1  | sed: can't read /home/steam/Zomboid/Server/SunnySideGaming.ini: No such file or directory
zomboid-server_1  | sed: can't read /home/steam/ZomboidDedicatedServer/ProjectZomboid64.json: No such file or directory
zomboid-server_1  | sed: can't read /home/steam/Zomboid/Server/SunnySideGaming.ini: No such file or directory
zomboid-server_1  | sed: can't read /home/steam/Zomboid/Server/SunnySideGaming.ini: No such file or directory
zomboid-server_1  | sed: can't read /home/steam/Zomboid/Server/SunnySideGaming.ini: No such file or directory
zomboid-server_1  | sed: can't read /home/steam/Zomboid/Server/SunnySideGaming.ini: No such file or directory
zomboid-server_1  | sed: can't read /home/steam/Zomboid/Server/SunnySideGaming.ini: No such file or directory
zomboid-server_1  | sed: can't read /home/steam/Zomboid/Server/SunnySideGaming.ini: No such file or directory
zomboid-server_1  | sed: can't read /home/steam/Zomboid/Server/SunnySideGaming.ini: No such file or directory
zomboid-server_1  |
zomboid-server_1  | ### Post Install Configuration applied.
zomboid-server_1  |
zomboid-server_1  | ### Starting Project Zomboid Server...
zomboid-server_1  | timeout: failed to run command '/home/steam/ZomboidDedicatedServer/start-server.sh': No such file or directory
project-zomboid_new_zomboid-server_1 exited with code 127
```

**To Reproduce**
1. use docker-compose with this file:
```
version: "3.8"

services:
  zomboid-server:
    image: renegademaster/zomboid-dedicated-server:1.5.0
    restart: unless-stopped
    user: "1000:1000"
    environment:
      ADMIN_PASSWORD: "redacted"
      ADMIN_USERNAME: "superuser"
      AUTOSAVE_INTERVAL: "15"
      GAME_VERSION: "public"
      MOD_NAMES: "PZRespawnRedux;BetterSortCC;manageContainers;ObviousRecipeChippedStone;ForagingBuff01;ATA_Bus;TMC_Trolley;VehiclePartsRepair;modoptions;TheStar;VehicleRecycling;DisableCarWear;82oshkoshM911"
      MOD_WORKSHOP_IDS: "2685600088;2313387159;2650547917;2704468416;2700569885;2592358528;2478768005;1558779191;2169435993;2619072426;2289429759;2444374984;2618213077"
      PAUSE_ON_EMPTY: "false"
      PUBLIC_SERVER: "true"
      QUERY_PORT: "16261"
      SERVER_NAME: "SunnySideGaming"
    ports:
      - "8766:8766/udp"
      - "8767:8767/udp"
      - "16261:16261/udp"
      - "16262-16272:16262-16272"
      - "27015:27015"
    volumes:
      - ./ZomboidDedicatedServer:/home/steam/ZomboidDedicatedServer
      - ./ZomboidConfig:/home/steam/Zomboid/
    cap_drop:
      - ALL
```

**Expected behavior**
Permissions are set

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu 18.04.02
 - Docker version 18.09.7, build 2d0083d
 - Image Version 1.5.0

**Additional context**
