### ISSUE TITLE
How to access server console to set admin

### ISSUE THREAD

**Issue by Rumsfield** [Renegade-Master/zomboid-dedicated-server#20]
I'm new to docker and I'm trying to figure out how to interact with the server console from an SSH terminal session. I'm using a VPS running Debian 10, and I've been able to run the docker compose file to bring up the container. The server works, I've played on it. But I just need to access the console.

When I run this command, I see the zomboid server print log messages during server startup. 
```
$ docker-compose up --build
Building zomboid-server
Sending build context to Docker daemon   72.7kB
...
Starting zomboid-dedicated-server_zomboid-server_1 ... done
Attaching to zomboid-dedicated-server_zomboid-server_1
zomboid-server_1  |
zomboid-server_1  | ### Setting variables...
zomboid-server_1  |
...
zomboid-server_1  | LOG  : General     , 1648929464158> 315,397,620> LuaNet: Initialization [DONE], triggering events for 'LuaNet.onInitAdd'.
zomboid-server_1  | LOG  : Network     , 1648929464158> 315,397,620> DISCORD: token not configured
zomboid-server_1  | LOG  : Network     , 1648929464158> 315,397,620> *** DISCORD DISABLED ****
zomboid-server_1  | LOG  : General     , 1648929464164> 315,397,627> ##########
zomboid-server_1  | Server Steam ID [removed]
zomboid-server_1  | ##########
zomboid-server_1  | LOG  : Multiplayer , 1648929464184> 315,397,646> [MPStatistics] mem usage notification threshold=4,080,218,880
zomboid-server_1  | LOG  : General     , 1648929464192> 315,397,654> RCON: listening on port 27015
zomboid-server_1  | LOG  : General     , 1648929465442> 315,398,904> 1648929465442 znet: OnPolicyResponse
zomboid-server_1  | LOG  : General     , 1648929465442> 315,398,904> 1648929465442 znet: Zomboid Server is VAC Secure
zomboid-server_1  | LOG  : General     , 1648929465568> 315,399,030> Unknown command process-status@eof
```

But I'm not able to enter any commands. Sorry if I'm missing something obvious, but could you please help me understand what's wrong?
![image](https://user-images.githubusercontent.com/13357300/161399375-20635099-67bd-425d-890a-9716d36931d4.png)

Here is the content of my docker-compose.yml:
```
version: "3.8"

services:
  zomboid-server:
    build:
      context: .
      dockerfile: docker/zomboid-dedicated-server.Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    restart: "no"
    user: "1000:1000"
    tty: true
    stdin_open: true
    environment:
      - "ADMIN_PASSWORD=[removed]"
      - "ADMIN_USERNAME=[removed]"
      - "AUTOSAVE_INTERVAL=15"
      - "BIND_IP=0.0.0.0"
      - "GAME_PORT=8766"
      - "GAME_VERSION=public"
      - "MAX_PLAYERS=16"
      - "MAX_RAM=4096m"
      - "MOD_NAMES="
      - "MOD_WORKSHOP_IDS="
      - "NO_CHOWN_CONFIG_DIR=false"
      - "NO_CHOWN_GAME_DIR=false"
      - "PAUSE_ON_EMPTY=true"
      - "PUBLIC_SERVER=true"
      - "QUERY_PORT=16261"
      - "RCON_PASSWORD=[removed]"
      - "RCON_PORT=27015"
      - "SERVER_NAME=[removed]"
      - "SERVER_PASSWORD=[removed]"
      - "STEAM_VAC=true"
      - "USE_STEAM=true"
    ports:
      - target: 8766
        published: 8766
        protocol: udp
      - target: 16261
        published: 16261
        protocol: udp
      - target: 27015
        published: 27015
        protocol: tcp
    volumes:
      - ./ZomboidDedicatedServer:/home/steam/ZomboidDedicatedServer
      - ./ZomboidConfig:/home/steam/Zomboid/
  ```
