### ISSUE TITLE
Server installation fails on K8s

### ISSUE THREAD

**Issue by Marahin** [Renegade-Master/zomboid-dedicated-server#26]
**Describe the bug**
Hello! 
I am trying to deploy PZ using this image on Kubernetes (with storage being mounted through NFS), however the installation steps are failing.

**To Reproduce**
1. Create all necessary Kubernetes manifests:
```yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    name: zomboid
  name: zomboid
  namespace: zomboid
spec:
  minReadySeconds: 30
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: zomboid
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      labels:
        name: zomboid
    spec:
      containers:
      - args: []
        env: []
        image: renegademaster/zomboid-dedicated-server:latest
        imagePullPolicy: Always
        name: zomboid
        ports:
        - containerPort: 8766
          name: game
        - containerPort: 16261
          name: query
        - containerPort: 27015
          name: rcon
        stdin: false
        tty: false
        volumeMounts:
        - mountPath: /home/steam/Zomboid
          name: config
        - mountPath: /home/steam/ZomboidDedicatedServer
          name: data
      imagePullSecrets: []
      initContainers: []
      securityContext:
        runAsGroup: 1017
        runAsUser: 1017
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: zomboid-config-pvc
      - name: data
        persistentVolumeClaim:
          claimName: zomboid-data-pvc
---
apiVersion: v1
kind: Namespace
metadata:
  annotations: {}
  labels:
    name: zomboid
  name: zomboid
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations: {}
  labels:
    name: zomboid-config-pv
  name: zomboid-config-pv
  namespace: zomboid
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  mountOptions:
  - nfsvers=4
  nfs:
    path: /mnt/ssd-pool/zomboid/config
    server: storagemaster.local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/mount-options: dir_mode=0777,file_mode=0777,uid=1017,gid=1017
  labels:
    name: zomboid-config-pvc
  name: zomboid-config-pvc
  namespace: zomboid
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: zomboid-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/mount-options: dir_mode=0777,file_mode=0777,uid=1017,gid=1017
  labels:
    name: zomboid-data-pvc
  name: zomboid-data-pvc
  namespace: zomboid
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeName: zomboid-data-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations: {}
  labels:
    name: zomboid-data-pv
  name: zomboid-data-pv
  namespace: zomboid
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  mountOptions:
  - nfsvers=4
  nfs:
    path: /mnt/ssd-pool/zomboid/data
    server: storagemaster.local
```
2. Ensure NFS is available and path `/mnt/ssd-pool/zomboid` has two subdirectories: `data` and `config`, both set to chown 1017:1017 (zomboid:zomboid)
3. Apply the manifests

**Expected behavior**
Container starting up, eventually running the server.

**Actual behavior**
Container fails to run `steamcmd.sh` due to lack of permissions (the script is owned by `steam:steam` user, and when I run `id steam` within the container, it resolves to `1000:1000` - while the container runtime is already set to `1017:1017`, which is `zomboid:zomboid` user).

```
### Setting variables...

### Updating Folder Permissions...

### Folder Permissions updated.

### Applying Pre Install Configuration...
sed: couldn't open temporary file /home/steam/sedABDtJB: Permission denied

### Pre Install Configuration applied.

### Updating Project Zomboid Server...
/home/steam/run_server.sh: line 130: /home/steam/steamcmd.sh: Permission denied

### Project Zomboid Server updated.

### Checking if this is the first run...

### This is the first run.
Starting server for 60 seconds

### Starting Project Zomboid Server...
timeout: failed to run command '/home/steam/ZomboidDedicatedServer/start-server.sh': No such file or directory

### Project Zomboid Server stopped.

### First run check complete.

### Applying Post Install Configuration...
/home/steam/Zomboid/Server/ZomboidServer.ini not found!
/home/steam/Zomboid/Server/ZomboidServer.ini not found!
/home/steam/Zomboid/Server/ZomboidServer.ini not found!
/home/steam/Zomboid/Server/ZomboidServer.ini not found!
/home/steam/Zomboid/Server/ZomboidServer.ini not found!
/home/steam/Zomboid/Server/ZomboidServer.ini not found!
/home/steam/Zomboid/Server/ZomboidServer.ini not found!
/home/steam/Zomboid/Server/ZomboidServer.ini not found!
/home/steam/Zomboid/Server/ZomboidServer.ini not found!
/home/steam/Zomboid/Server/ZomboidServer.ini not found!
/home/steam/Zomboid/Server/ZomboidServer.ini not found!
/home/steam/Zomboid/Server/ZomboidServer.ini not found!
sed: can't read /home/steam/ZomboidDedicatedServer/ProjectZomboid64.json: No such file or directory

### Post Install Configuration applied.

### Starting Project Zomboid Server...
timeout: failed to run command '/home/steam/ZomboidDedicatedServer/start-server.sh': No such file or directory

### Project Zomboid Server stopped.
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: (microk8s) Kubernetes (running on top of Ubuntu 20.04) 
 - Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.6-2+2a84a218e3cd52", GitCommit:"2a84a218e3cd52ee62c7c5aeb40c7281d5c5b0a0", GitTreeState:"clean", BuildDate:"2022-04-28T11:15:42Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
- Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.6-2+2a84a218e3cd52", GitCommit:"2a84a218e3cd52ee62c7c5aeb40c7281d5c5b0a0", GitTreeState:"clean", BuildDate:"2022-04-28T11:13:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
 - Docker Version [e.g. 20.10.12]
 - Image Version [e.g. 1.0.0]

**Additional context**
