### ISSUE TITLE
start-server.sh permission denied

### ISSUE THREAD

**Issue by Hibanan** [Renegade-Master/zomboid-dedicated-server#32]
docker log output (truncated): 
```
zomboid                     | Success! App '380870' fully installed.
zomboid                     | quit
zomboid                     |
zomboid                     | ### Project Zomboid Server updated.
zomboid                     |
zomboid                     | ### Checking if this is the first run...
zomboid                     |
zomboid                     | ### This is not the first run.
zomboid                     |
zomboid                     | ### First run check complete.
zomboid                     |
zomboid                     | ### Applying Post Install Configuration...
zomboid                     |
zomboid                     | ### Post Install Configuration applied.
zomboid                     |
zomboid                     | ### Starting Project Zomboid Server...
zomboid                     | timeout: failed to run command '/home/steam/ZomboidDedicatedServer/start-server.sh': Permission denied
zomboid                     |
zomboid                     | ### Project Zomboid Server stopped.
```

relevant file permissions:

`-rwxr-xr-x  1 tom tom 1.2K Jul 30 02:08 start-server.sh`

For the record, everything else is successfully accessed.

docker-compose.yml used to start the server:

```
version: '2.4'
services:
    zomboid-dedicated-server:
        ports:
            - '16261:16261/udp'
            - '8766:8766/udp'
        environment:
            - ADMIN_PASSWORD=N/A
            - PAUSE_ON_EMPTY=false
            - STEAM_VAC=false
            - SERVER_NAME=N/A
            - SERVER_PASSWORD=N/A
        volumes:
            - /home/tom/nvme/zomboid/ZomboidConfig:/home/steam/Zomboid
            - /home/tom/nvme/zomboid/ZomboidDedicatedServer:/home/steam/ZomboidDedicatedServer
        container_name: zomboid
        user: 1000:1000
        image: 'renegademaster/zomboid-dedicated-server:latest'
        restart: unless-stopped
        network_mode: host
        cpu_shares: 4096
```

P.s.: Yes, I'm aware you don't need to expose ports with `network_mode:host`
