### ISSUE TITLE
Server not showing up and can't be connected to

### ISSUE THREAD

**Issue by pcbmaster** [Renegade-Master/zomboid-dedicated-server#48]
Having issues with the docker image.  Everything seems to work fine, getting all the way to the end, ports are open, but I can't directly connect to the server, nor can I see it in the list.

```
version: "3.3"
services:
  zomboid:
    image: renegademaster/zomboid-dedicated-server:latest
    volumes:
      - /root/zomboid/ZomboidDedicatedServer:/home/steam/ZomboidDedicatedServer:rw
      - /root/zomboid/ZomboidConfig:/home/steam/Zomboid:rw
    ports:
      - 16261:16261
      - 16262:16262
    environment:
      ADMIN_PASSWORD: "blabla"
      ADMIN_USERNAME: "redacted"
      SERVER_NAME: "Me Server"
      SERVER_PASSWORD: "password"
```

apologies if it's something really obvious, but I followed all the instructions, including making the folders.
