### ISSUE TITLE
SQL Exceptions in logs - Prevents player join

### ISSUE THREAD

**Issue by pcbmaster** [Renegade-Master/zomboid-dedicated-server#51]
**Describe the bug**
Steam clients connecting via "Use Steam Relay" receive a disconnect stating they are banned with the following entry in the log
```
zomboid_1  | LOG  : General     , 1668464649002> 226,671,698> Steam client *redacted* is initiating a connection.
zomboid_1  | ERROR: General     , 1668464649006> 226,671,701> org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: bannedid)
zomboid_1  | ERROR: General     , 1668464649007> 226,671,702>   at org.sqlite.core.DB.newSQLException(DB.java:941)
zomboid_1  | ERROR: General     , 1668464649007> 226,671,702>   at org.sqlite.core.DB.newSQLException(DB.java:953)
zomboid_1  | ERROR: General     , 1668464649007> 226,671,703>   at org.sqlite.core.DB.throwex(DB.java:918)
zomboid_1  | ERROR: General     , 1668464649007> 226,671,703>   at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
zomboid_1  | ERROR: General     , 1668464649008> 226,671,703>   at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
zomboid_1  | ERROR: General     , 1668464649008> 226,671,704>   at org.sqlite.core.DB.prepare(DB.java:257)
zomboid_1  | ERROR: General     , 1668464649008> 226,671,704>   at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47)
zomboid_1  | ERROR: General     , 1668464649009> 226,671,704>   at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
zomboid_1  | ERROR: General     , 1668464649012> 226,671,708>   at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
zomboid_1  | ERROR: General     , 1668464649013> 226,671,708>   at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
zomboid_1  | ERROR: General     , 1668464649013> 226,671,709>   at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
zomboid_1  | ERROR: General     , 1668464649014> 226,671,709>   at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
zomboid_1  | ERROR: General     , 1668464649015> 226,671,710>   at zombie.network.ServerWorldDatabase.authClient(ServerWorldDatabase.java:749)
zomboid_1  | ERROR: General     , 1668464649015> 226,671,710>   at zombie.core.znet.SteamUtils.clientInitiateConnectionCallback(SteamUtils.java:266)
zomboid_1  | ERROR: General     , 1668464649016> 226,671,711>   at zombie.core.raknet.RakNetPeerInterface.TryReceive(Native Method)
zomboid_1  | ERROR: General     , 1668464649016> 226,671,711>   at zombie.core.raknet.RakNetPeerInterface.Receive(RakNetPeerInterface.java:137)
zomboid_1  | ERROR: General     , 1668464649017> 226,671,712>   at zombie.core.raknet.UdpEngine.Receive(UdpEngine.java:427)
zomboid_1  | ERROR: General     , 1668464649017> 226,671,713>   at zombie.core.raknet.UdpEngine.threadRun(UdpEngine.java:97)
zomboid_1  | ERROR: General     , 1668464649018> 226,671,713>   at java.base/java.lang.Thread.run(Unknown Source)
zomboid_1  | LOG  : Network     , 1668464649018> 226,671,714> [14-11-22 22:24:09.018] > ZNet: Sending ban message: 1
zomboid_1  | LOG  : Network     , 1668464649019> 226,671,715> [14-11-22 22:24:09.019] > ZNet: hnote over CZombienet : **ZNetAuthFailedMessage(afSteamIDBanned)**
zomboid_1  | LOG  : Network     , 1668464649020> 226,671,715> [14-11-22 22:24:09.020] > ZNet: SZombienet -> SZombienet: SendServerMessage
zomboid_1  | LOG  : Network     , 1668464656765> 226,679,460> [14-11-22 22:24:16.765] > ConnectionManager: [disconnect] "connection-attempt-timeout" connection: guid=22518010463278463 ip=null steam-id=0 access= username="null" connection-type="Disconnected"
```

**To Reproduce**
1. Make user folders
2. Create fresh container using the following docker-compose file
```
version: "3.3"
services:
  zomboid:
    image: renegademaster/zomboid-dedicated-server:latest
    volumes:
      - /root/zomboid/ZomboidDedicatedServer:/home/steam/ZomboidDedicatedServer:rw
      - /root/zomboid/ZomboidConfig:/home/steam/Zomboid:rw
    ports:
      - 16261:16261/udp
      - 16262:16262/udp
      - 27015:27015/tcp
    environment:
      ADMIN_PASSWORD: "blabla"
      ADMIN_USERNAME: "redacted"
      SERVER_NAME: "Me Server"
      SERVER_PASSWORD: "password"
      UDP_PORT: 16262
      PUBLIC_SERVER: "true"
      RCON_PASSWORD: "password"
      RCON_PORT: 27015
      USE_STEAM: "true"
```

**Expected behavior**
`PUBLIC_SERVER: "true"` should not be using whitelist, no SQL exceptions should be in logs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 7
 - Docker Version: `20.10.5+dfsg1, build 55c4c88`
 - Image Version: `latest`

**Additional context**
DB file for server is completely empty. Replacing the db file with a valid one from a local save fixes this issue.
